### ISSUE TITLE
Docker image does not expose a /api endpoint

### ISSUE THREAD

**Issue by npahucki** [onflow/fcl-dev-wallet#110]
Steps to reproduce: 

```
docker compose up
```

Open browser to http://localhost:8701/api OR http://localhost:8701/harness

Expected: A 200 response with JSON

Actual: A 404 response

**Comment by 10thfloor** [comment]
The `/api` endpoint is only meant to be used by the flow-cli. The request should 404 when the app is run from source (locally of via Docker) and the default config will be returned, so you should be fine.

This isn't obvious though, and we're rethinking how this is designed so we can avoid confusion.

**Comment by dangdennis** [comment]
I've just setup the local dev wallet for the first time. The docker compose didn't work as noted, but `flow dev-wallet` and `flow emulator` seems to be happiest path here.

**Comment by justinbarry** [comment]
The API endpoint has been replaced with an all static build.
