### ISSUE TITLE
Dev-Wallet does not work when run from source. 

### ISSUE THREAD

**Issue by 10thfloor** [onflow/fcl-dev-wallet#111]
A few users have encountered an issue with the `/api` endpoint resulting in not being able to use the dev-wallet when it is run from source (using `npm run dev`)

Reproduction: 
- Clone and run the dev wallet source code using `npm run dev`
- Attempt to use the wallet from a 3rd party application (like Kitty Items or a test harness on a different host)
- Observe the wallet does not load, and there is an error in the browser console

Requirements: 
- The wallet should be usable from external applications when running from source using `npm run dev`

**Comment by gregsantos** [comment]
Closing as this seems fixed in latest static branch
@10thfloor can you merge when you are free?
