### ISSUE TITLE
Parameterize the accessNode

### ISSUE THREAD

**Issue by kmcintyre** [onflow/fcl-dev-wallet#112]
https://github.com/onflow/fcl-dev-wallet/blob/main/cmd/main.go

It's not up to the maintainers to decide how users should use this code.  I don't understand why I have to run my emulator on localhost...when a team might want a share an emulator.

**Comment by justinbarry** [comment]
@kmcintyre Are you running the emulator via the flow cli?

**Comment by sideninja** [comment]
@kmcintyre you are right, this was just meant to be for simple testing, but if you see the value we could support passing the parameters, but in that case you can also use the dev-wallet integrated into the CLI, using `flow dev-wallet` and then pass the parameters, you can also run the dev-wallet as a standalone using the `npm run` command, again this was solely for testing.

**Comment by smeet2804** [comment]
Hello @sideninja , How do I pass the parameters (IP address and port)?

**Comment by smeet2804** [comment]
Hello @kmcintyre, were you able to achieve any solution or alternative for that?

**Comment by kmcintyre** [comment]
Yes running emulator via cli locally, but would like to a shared emulator
for testing purposes

**Comment by sideninja** [comment]
implemented #515
