### ISSUE TITLE
[Error Code: 1101] cadence runtime error Execution failed: error: cannot find declaration `FCLCrypto` in `74daa6f9c7ef24b1.FCLCrypto`

### ISSUE THREAD

**Issue by Alio-Kh** [onflow/fcl-dev-wallet#125]
Got this error when trying to sign a message : 
```
[Error Code: 1101] cadence runtime error Execution failed:
error: cannot find declaration FCLCrypto in 74daa6f9c7ef24b1.FCLCrypto
```

flow-cli: v0.37.3

**Comment by gregsantos** [comment]
Currently the [FCLCrypto contract](https://github.com/onflow/fcl-dev-wallet/blob/main/cadence/contracts/FCLCrypto.cdc) required for user signature verification is not deployed automatically when emulator is started. There is an [issue](https://github.com/onflow/flow-emulator/issues/159) raised to get this added.
Deploy this contract manually and you should be good.

```js
flow accounts add-contract FCLCrypto ./path/to/FCLCrypto.cdc
```
