### ISSUE TITLE
Further explanation of integration to local environment and use cases needed.

### ISSUE THREAD

**Issue by srinjoyc** [onflow/fcl-dev-wallet#14]
The README.md should answer some more questions:

1. What is the purpose of this fcl-dev-wallet in terms of use cases? IE. Is this so you can try out your local authentication flow? What else can you do?

2. What does the harness enable? Had to download from another repo to use but unsure of what it does? Can this be bundled in as pre-script? 

3. How are the apps (emulator, kitty-items, harness) communicating? Could we show a diagram of how it's connected?

**Comment by gpavlov2016** [comment]
Changing priority to low. Planning to do the documentation update using our contractors (tanuki team) with Mack's supervision
