### ISSUE TITLE
`go-server` script target doesn't work when working from a fresh install

### ISSUE THREAD

**Issue by justinbarry** [onflow/fcl-dev-wallet#143]
Currently the `go-server` script target throws an error message instructing the user to run `go get github.com/onflow/fcl-dev-wallet/go/wallet` on a fresh install. 

Should this be made to run as part of the `go-server` script target?

For reference see: https://github.com/onflow/fcl-dev-wallet/pull/137#issuecomment-1196405943

**Comment by sideninja** [comment]
It could be added to readme or install script, but not part of go-server command since this doesn't need to be run everytime. You just need to install it. The setup part is not automated as it's written in docs but that might be missing there so good idea to add it somwhere.
