### ISSUE TITLE
Avatar URL is undefined

### ISSUE THREAD

**Issue by bartolomej** [onflow/fcl-dev-wallet#153]
I'm using the latest version of flow-cli (`v0.40.0`).

When I open the dev-wallet modal, custom avatar icons aren't shown (on any dev-wallet modal UI). 

![Screenshot 2022-09-28 at 12 24 31](https://user-images.githubusercontent.com/36109955/192755730-1cf781c2-41fb-407d-90c8-7de0a090b318.png)

After closer inspection, I can see that an invalid avatar URL is requested:

![Screenshot 2022-09-28 at 12 12 59](https://user-images.githubusercontent.com/36109955/192753457-dc3f53da-e2b6-41e9-9108-3bb9d28617b0.png)

**Comment by huyndo** [comment]
Is this still happening for you @bartolomej? I'm trying to reproduce it on my end but I'm having no luck.
