### ISSUE TITLE
Authn modal not shown because of an initialization error?

### ISSUE THREAD

**Issue by bartolomej** [onflow/fcl-dev-wallet#154]
## Description

While testing the Flower app we discovered this issue where the dev-wallet authorization modal doesn't seem to show occasionally (after a call to `fcl.authenticate`).

In the below demo, when "Connect wallet" is clicked [the `fcl.authenticate` function is called](https://github.com/onflowser/flowser/blob/5aa966dda6f9832da50a8ecab357d17206b7d716/frontend/src/hooks/use-flow.ts#L101-L105). After that nothing seems to happen (except the UI dims a little).

https://user-images.githubusercontent.com/36109955/192762063-6dd15f9d-7d72-4e03-8c92-375ee4b92132.mov

I checked the network logs, all the request to dev-wallet server succeeded. But what I think is causing this issue is some dev-wallet initialization error, that doesn't get handled properly.

So I saw that `fcl/authn` page component is wrapped in `AuthnContextProvider`. This provider also handles the FCL initialization logic:

https://github.com/onflow/fcl-dev-wallet/blob/a409ad0832bee2f224a52bfad23c2b898339dd5d/contexts/AuthnContext.tsx#L26-L37

And what seems to happen is that in case the `initializeWallet` function throws an error, the `isInitialized` function is never set to `false`. Because of that, this provider always returns `null` and the children never get rendered - that's probably why the blank screen was shown.

https://github.com/onflow/fcl-dev-wallet/blob/a409ad0832bee2f224a52bfad23c2b898339dd5d/contexts/AuthnContext.tsx#L21

https://github.com/onflow/fcl-dev-wallet/blob/a409ad0832bee2f224a52bfad23c2b898339dd5d/contexts/AuthnContext.tsx#L39

There is still a question of why the initialization failed. I will try to look into that aswell.

## Expected outcome

I would expect that all errors are properly handled. In case of an error, we should show a user-friendly error message and optionally also a developer-friendly error message in the console (with more context).

## Context

I'm using dev-wallet from the latest version of flow-cli (v0.40.0).

This issue is blocking us from releasing the beta version of Flowser desktop app, in the scope of https://github.com/onflow/developer-grants/issues/27.

**Comment by bartolomej** [comment]
For some context on the dev-wallet initialization failure issue. I also see these logs when I trigger `fcl.authenticate`:

```
➜  flowser ✗ flow emulator
INFO[0000] ⚙️   Using service account 0xf8d6e0586b0a20c7  serviceAddress=f8d6e0586b0a20c7 serviceHashAlgo=SHA3_256 servicePrivKey=0660f98a97d73a374bab87d5b21d06a2a9285e6a71ca75babec113badb6ba58c servicePubKey=588e7f586822522b63e350f47efd9dd51fc04981614eb9eec55a6733dfe14a0de8fa9b53909120dd9dd4bd39ca16322d0d0708705f53ba3b76a90806246f0885 serviceSigAlgo=ECDSA_P256
INFO[0000] 📜  Flow contract                              FlowServiceAccount=0xf8d6e0586b0a20c7
INFO[0000] 📜  Flow contract                              FlowToken=0x0ae53cb6e3f42a79
INFO[0000] 📜  Flow contract                              FungibleToken=0xee82856bf20e2aa6
INFO[0000] 📜  Flow contract                              FlowFees=0xe5a8b7f23e8b548f
INFO[0000] 📜  Flow contract                              FlowStorageFees=0xf8d6e0586b0a20c7
INFO[0000] 🌱  Starting gRPC server on port 3569          port=3569
INFO[0000] 🌱  Starting REST API on port 8888             port=8888
INFO[0000] 🌱  Starting admin server on port 8080         port=8080
INFO[0022] ⭐  Transaction executed                       computationUsed=54 txID=88c36d251b0303618afd68c29290ea54e44c636c35539648a66d45c6f9730359
INFO[0022] ⭐  Script executed                            scriptID=9f27bcf1d399d777a8b9c7c08c9ee3e9a4346820c29af2247b86781d509104df
WARN[0022] ❗  Script reverted                            scriptID=52b9bcd485cb5f37a913feac6facb96dcdf692d3b8377d47e29d000bd93dc3e1
WARN[0022] ERR [52b9bc] [Error Code: 1101] cadence runtime error Execution failed:
error: invalid script return type: `PublicAccount`
--> 52b9bcd485cb5f37a913feac6facb96dcdf692d3b8377d47e29d000bd93dc3e1
WARN[0022] ❗  Script reverted                            scriptID=52b9bcd485cb5f37a913feac6facb96dcdf692d3b8377d47e29d000bd93dc3e1
WARN[0022] ERR [52b9bc] [Error Code: 1101] cadence runtime error Execution failed:
error: invalid script return type: `PublicAccount`
--> 52b9bcd485cb5f37a913feac6facb96dcdf692d3b8377d47e29d000bd93dc3e1
```

I don't know if this is even related to the initialization, but it definitely seems something is up.

To reproduce this, I just ran `flow emulator` and `flow dev-wallet` with flow-cli@v0.40.0.

This is the `flow.json` config that I used:
```json
{
	"networks": {
		"emulator": "127.0.0.1:3569",
		"mainnet": "access.mainnet.nodes.onflow.org:9000",
		"testnet": "access.devnet.nodes.onflow.org:9000"
	},
	"accounts": {
		"emulator-account": {
			"address": "f8d6e0586b0a20c7",
			"key": "0660f98a97d73a374bab87d5b21d06a2a9285e6a71ca75babec113badb6ba58c"
		}
	}
}
```

**Comment by gregsantos** [comment]
Hmm, sorry you're having this issue, I am having trouble recreating this issue locally @bartolomej
Will have to dig in...Those emulator errors are intermittent?

**Comment by bartolomej** [comment]
Yes, those emulator errors seem to happen on a regular basis. Although the fcl-dev-wallet initialization issue (when the modal doesn't appear) happens only sometimes.

I created a minimal reproducible example here: https://github.com/bartolomej/fcl-dev-wallet-issue

Let me know if you need any more context!

**Comment by gregsantos** [comment]
After some investigation, it seems there may be an issue witha a mismatched Cadence version in the emulator.
While that is being looked into, can you please try running dev-wallet from source. I was able to use it successfully with your example.
1. Make sure the flow.json and .env.development vars match your emulator keys
2. Disable cache in the browser network tab

**Comment by gregsantos** [comment]
A couple other notes...
Running flow-cli @ versions previous 0.40.0, does not produce any error.
Running flow-cli@v0.41.0 does not produce the UI bug, but does introduce the PublicAccount problem

**Comment by bartolomej** [comment]
> After some investigation, it seems there may be an issue witha a mismatched Cadence version in the emulator. While that is being looked into, can you please try running dev-wallet from source. I was able to use it successfully with your example.
> 
> 1. Make sure the flow.json and .env.development vars match your emulator keys
> 2. Disable cache in the browser network tab

I tried running dev wallet from source as you suggested and haven't seen the UI bug (blank dark screen) when calling `fcl.authenticate`. 

Although the UI bug still appeared for some other error (I think it was the `Invalid envelope key` error). I know this error is on my side (probably due to the misconfigured dev wallet env vars), but I still think that the blank screen should never appear (even in case of an error on the user's side).

Also while doing some general testing last week, I noticed that the dev wallet authentication popup sometimes took a few seconds (e.g. up to 5s) to appear. I'm thinking it might be smart to show a loading state before the popup is shown (state is loaded/initialized). What do you think?

**Comment by bartolomej** [comment]
> A couple other notes... Running flow-cli @ versions previous 0.40.0, does not produce any error. Running flow-cli@v0.41.0 does not produce the UI bug, but does introduce the PublicAccount problem

Hmm, weird that you couldn't reproduce those issues with flow-cli@0.40.0. I'm definitely experiencing those issues on that version as well.

**Comment by bartolomej** [comment]
@gregsantos Awesome, good to hear!

As for the UI/UX issue, it's also amazing to hear that you are already working on these improvements! I also added a very simple (demo) implementation myself here: https://github.com/onflow/fcl-dev-wallet/pull/155

I believe adding error handling to the root components (e.g. `AuthContextProvider`) is probably the highest priority (added this to the example), as I've seen unhandled errors happening quite frequently in practice.

My example only shows the loading and error states in plain text, but I believe that wrapping those in some kind of dismissable component could be pretty useful (e.g. when dev-wallet encounters an init error, user's should be able to dismiss it to not be stuck in that state).

I'd love to help out here whenever I can, but should probably wait for more updates on this from your side, so I don't make any duplicate work!

**Comment by gregsantos** [comment]
Thanks for opening that draft PR @bartolomej 
Please feel free to complete it to you ability an we'll review asap!

**Comment by bartolomej** [comment]
@gregsantos Awesome, I think it should be ready for review as of this weekend.

**Comment by huyndo** [comment]
@bartolomej I made some comments in that PR. Feel free to take a look and lmk what you think.

**Comment by bartolomej** [comment]
@gregsantos  Reopening this issue, as it looks like the initialization error wasn't (the only) cause of the modal not showing.

I managed to again reproduce this issue a few times, but have no clue what's happening yet:

https://user-images.githubusercontent.com/36109955/197764239-aec3f97e-07ed-42ca-a443-7f6dfa577390.mov

A couple notes:
- The emulator is online and both GRPC and REST APIs are accessible
- Root nextjs app element has no children

**Comment by gregsantos** [comment]
Thanks @bartolomej That caching really seems like the culprit here. Assigning @huyndo to take another look. Please share any updates.

**Comment by bartolomej** [comment]
@gregsantos Yeah surely seems like it. Mentioning another related issue that I submitted: https://github.com/onflow/fcl-dev-wallet/issues/158

**Comment by bartolomej** [comment]
@gregsantos Any updates on this? I haven't been able to look into it further, but will try in the next few days,

**Comment by gregsantos** [comment]
Thanks @bartolomej @huyndo may have time to check this soon

**Comment by bartolomej** [comment]
@huyndo Hmm, I think I don't remember any. I re-watched the video from https://github.com/onflow/fcl-dev-wallet/issues/154#issuecomment-1290418147, and it also looks like there are no errors in console, as otherwise it should show a red notification in the header afaik:
![Screenshot 2022-11-10 at 11 47 52](https://user-images.githubusercontent.com/36109955/201071310-326d4339-44cf-428b-b1c4-de1182cd04a4.png)

**Comment by huyndo** [comment]
@bartolomej Turns out it was some error in loading config. The caching PR #162 should fix this one for you though.
