### ISSUE TITLE
emulator show ERR when fcl-dev-wallet start 

### ISSUE THREAD

**Issue by script-money** [onflow/fcl-dev-wallet#18]
I follow README to run dev-wallet, show message below every time in emulator. Website can show wallet informations.
Because lack use cases in document, so I am not sure this error if make wallet available.
fcl-dev-wallet: d33e4b5
flow-cli: Version: v0.21.0
```
WARN[0070] ❗  Script reverted                            scriptID=66fdac04a26c50654b5ea571689118c65d7143d70c107d74612680cc3d70ca63
WARN[0070] ERR [66fdac] [Error Code: 1101] cadence runtime error Execution failed:
error: cannot find declaration `FCL` in `f8d6e0586b0a20c7.FCL`
 --> 66fdac04a26c50654b5ea571689118c65d7143d70c107d74612680cc3d70ca63:1:7
  |
1 | import FCL from 0xf8d6e0586b0a20c7
  |        ^^^ available exported declarations are:
```

**Comment by decentMorgan** [comment]
Yup, I get the same error. This goes away after I got to `/harness` and log in. Then accounts get created and `FCL` can be imported.

**Comment by fubz** [comment]
/harness login takes me back to my webapps page and 404s..... Dev wallet has a strange redirect.

**Comment by justinbarry** [comment]
I believe this has been addressed. If it hasn't please feel free to file another issue.
