### ISSUE TITLE
Initialization Error

### ISSUE THREAD

**Issue by chasefleming** [onflow/fcl-dev-wallet#180]
![Screen Shot 2023-01-12 at 2 29 13 PM](https://user-images.githubusercontent.com/1666730/212194593-efa15f7f-e403-4bdb-b718-57fa4c2531c9.png)

**Comment by gregsantos** [comment]
I'm getting this error as well on Flow CLI beta version and [Version 0.44.1](https://github.com/onflow/flow-cli/releases/tag/untagged-23190f5c6031b7664dcf)
Only on first load of dev wallet when running `flow dev-wallet`
