### ISSUE TITLE
INVARIANT encodeKey(key, curve, hash,weight) -- invalid key Error

### ISSUE THREAD

**Issue by jochasinga** [onflow/fcl-dev-wallet#62]
After running the fcl-dev-wallet locally with:

```shell
npm run start 
```
and set up the variables `FLOW_ACCOUNT_PRIVATE_KEY`, `FLOW_ACCOUNT_PUBLIC_KEY`, and `FLOW_ACCOUNT_ADDRESS` in `.env.example` to match the running emulator. On the call to `fcl.logIn()`, I got the following error on the Next server:

```shell
Error: INVARIANT encodeKey(key, curve, hash, weight) -- invalid key (expecting type of string)
    at Object.exports.invariant (/home/my-user/Code/flow/fcl-dev-wallet/node_modules/@onflow/util-invariant/dist/util-invariant.js:1:48)
    at exports.encodeKey (/home/my-user/Code/flow/fcl-dev-wallet/node_modules/@onflow/util-encode-key/dist/util-encode-key.js:1:250)
    at encodeServiceKey (/home/my-user/Code/flow/fcl-dev-wallet/.next/server/chunks/450.js:76:76)
    at init (/home/my-user/Code/flow/fcl-dev-wallet/.next/server/pages/api/init.js:50:536)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

It appeared this is from `fcl.logIn()` sending a GET request to `http://localhost:8701/api/accounts` which returned 500.

I'm running this locally because I couldn't connect to port 8701 on the Docker version at all.

OS: Ubuntu 20.04 LTS
Node v12.22.5 LTS/erbium

**Comment by bluesign** [comment]
you need to rename .env.example to .env.local

**Comment by jochasinga** [comment]
Thanks now that seems to work @bluesign. However, on the browser the GET request to `http://localhost:8701/api/accounts` still returns 500. What is this request?

**Comment by bluesign** [comment]
I am on mobile, but there were some prefixes on some env variables, something like next_public on some of then if you remove that it is working.

**Comment by bluesign** [comment]
@jochasinga any log on console when you are making the request?

**Comment by jochasinga** [comment]
Confirm that this error no longer shows on the console for me. Closing this issue.

**Comment by jochasinga** [comment]
Reopening this because running this on Docker causes the same issue.

```shell
docker run -p 8701:8701 ghcr.io/onflow/fcl-dev-wallet:latest
```

When the modal launches, the GET request to `http://localhost:8701/api/accounts` returns 500 Internal Server Error on the browser's console and causs the aforementioned `invalid key Error`. Here is a log on the console:

```shell
GET http://localhost:8701/api/accounts 500 (Internal Server Error)
```

Note: If run without the `-p` flag, the React app won't be able to connect on `localhost:8701` at all. Probably not surprising for other experienced with Docker but worth documenting.

By far the only solution that worked was to change `.env.example` to `.env.local` and run the repo locally with `PORT=8701 npm run start`.

**Comment by bluesign** [comment]
@jochasinga 
you tried running like: 

```
docker run -it \
    -e PORT=8701 \
    -e FLOW_ACCESS_NODE=http://emulator:8080 \
    -e FLOW_ACCOUNT_KEY_ID=0 \
    -e FLOW_ACCOUNT_PRIVATE_KEY=4f82df6790f07b281adb5bbc848bd6298a2de67f94bdfac7a400d5a1b893de5 \
    -e FLOW_ACCOUNT_PUBLIC_KEY=519e9fbf966c6589fafe60903c0da5f55c5cb50aee5d870f097b35dfb6de13c170718cd92f50811cdd9290e51c2766440b696e0423a5031ae482cca79e3c479 \       -e FLOW_INIT_ACCOUNTS=0 \
    -e FLOW_ACCOUNT_ADDRESS=0xf8d6e0586b0a20c7 \
    -e FLOW_AVATAR_URL=https://avatars.onflow.org/avatar/ \
    ghcr.io/onflow/fcl-dev-wallet:latest 
```

**Comment by 10thfloor** [comment]
The intention was for user's to simply run the Docker image and get on with their lives. It should not be necessary to clone and build the project yourself. 🤔

The environment variables are included in the build process for the image and shouldn't need to be specified on the command line, unless you're overriding them.

**Comment by 10thfloor** [comment]
I think the problem might be renaming the .env.example to .env.local so the nextJS build picks them up during the image build process.

**Comment by jochasinga** [comment]
@10thfloor was it possible that in the build for `ghcr.io/onflow/fcl-dev-wallet:latest` the variables on `env.example` wasn't picked up by the app? I have success running the repo locally when changing it to `.env.local`.

**Comment by veeran-kochatech** [comment]
@bluesign im also facing the same issue
on using flow dev-wallet getting the below error on console

- http://localhost:8701/api returns 404 
- Failed to fetch config from API. Are you sure the dev-web-server is running on port 8701?
            SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
<img width="1440" alt="Screenshot 1944-03-14 at 11 31 49 AM" src="https://user-images.githubusercontent.com/97584756/171986772-0f38000c-c560-4161-a61a-e56fe8263148.png">

**Comment by gregsantos** [comment]
@veeran-kochatech Can you please try with the [latest release](https://github.com/onflow/fcl-dev-wallet/releases/tag/v0.4.3)

**Comment by gregsantos** [comment]
Update and resolved
