### ISSUE TITLE
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped

### ISSUE THREAD

**Issue by veeran-dev** [onflow/fcl-dev-wallet#71]
Hi Team,

I am using macOS Big Sur ( Apple M1 Chip )

On Docker amd64 warning is shown.

How do i resolve this issue
I tried updating docker-compose.yml with platform: linux/amd64 and platform: linux/arm64 both are not working.

Is there is any solution to sort this issue.

<img width="1440" alt="Screenshot 2021-10-21 at 1 28 59 AM" src="https://user-images.githubusercontent.com/25120085/138331596-98c27236-6198-43e8-9df7-b46c7b384bcc.png">

**Comment by bluesign** [comment]
I checked this recently, it was about IIRC node version on Docker container, but not debugged much. I will check again and get back to you

**Comment by fcoury** [comment]
@veeran-dev @bluesign I can confirm that upgrading manually to the latest version fixed the problem for me. It seems my upgrade was somewhat stuck, so I downloaded Docker Desktop from the website and it worked first time.
