### ISSUE TITLE
Latest Docker Image does not work with CLI

### ISSUE THREAD

**Issue by samwise2** [onflow/fcl-dev-wallet#74]
Steps to repro:

1. `flow emulator`
2. `docker run ghcr.io/onflow/fcl-dev-wallet:latest`

The docker run seems to work fine, and yields : `ready - started pm server 0.0.0.0:8701, url: http://localhost:8701`

But running `curl http://localhost:8701`, yields not found.

Our only suspicion for why this is the case, is because we believe that the keys that our `emulator-account` is using are different than the keys that are in the config files in the latest image. But, this is surprising because running the docker command above gives a successful "ready" result.

We would greatly appreciate some help with getting this working!

**Comment by bluesign** [comment]
hey @samwise2, I think you need to expose port with docker. 

https://docs.docker.com/config/containers/container-networking/

**Comment by samwise2** [comment]
Awesome, thanks @bluesign that worked! Can we get the README updated with:

`docker run -p -p 8701:8701 ghcr.io/onflow/fcl-dev-wallet:latest` so that people don't run into this in the future?

**Comment by samwise2** [comment]
Or at least some comment on this

**Comment by bluesign** [comment]
@samwise2 sure I think Flow Team will see the issue and they will update. Just incase I am tagging @10thfloor

**Comment by samwise2** [comment]
Great, thanks

**Comment by justinbarry** [comment]
Looks like this has been addressed.
