### ISSUE TITLE
Error when displaying authorizer that was not created by the dev wallet

### ISSUE THREAD

**Issue by chriswayoub** [onflow/fcl-dev-wallet#87]
If you sign a transaction with an account that was not created by the dev wallet (for instance, a server-side service account that is used in multi-sig transactions), there is a browser error when trying to render the authz details. I am not sure what else this affects or the best way to go about fixing it throughout the entire application, but I will submit a quick-fix PR that resolves the issue for my specific use-case in case it is helpful.

**Comment by justinbarry** [comment]
@chriswayoub Do you have a specific set of steps I can use to recreate this scenario?

**Comment by justinbarry** [comment]
Closing as stale
