### ISSUE TITLE
Images not loading on localhost

### ISSUE THREAD

**Issue by alxflw** [onflow/fcl-dev-wallet#90]
I'm working on a nextjs app locally and noticed that the images in the UI aren't loading. I checked out the image sources it looks for it there seems to be an assumption that relative paths like `/expand.svg` should be served, which isn't always the case.

<img width="514" alt="Screen Shot 2022-01-20 at 6 49 19 AM" src="https://user-images.githubusercontent.com/97620081/150362355-2d19fbc2-24de-427d-bb8e-999bdee9adff.png">

**Comment by justinbarry** [comment]
Looks like this has been addressed. Please file another issue if this I am mistaken.
