### ISSUE TITLE
Refresh endpoint always returns service account auth

### ISSUE THREAD

**Issue by arturenault** [onflow/fcl-dev-wallet#91]
The refresh endpoint always returns the service account address: https://github.com/onflow/fcl-dev-wallet/blob/main/pages/api/refresh.ts#L38

This means that whenever I try to create a new transaction using `fcl.mutate()`, the current user changes to the service account. This makes it impossible to sign transactions with any other account.

This doesn't repro in the test harness because the version of `onflow/fcl` we're using doesn't implement refresh yet.

**Comment by alse** [comment]
Thanks @arturenault , #92 will make the refresh endpoint dynamic and update the harness fcl
